const restaurantData = [
    { id: 1, name: "금호식당", breakfast: 'O', lunch: 'O', dinner: 'O', category: "기타" },
    { id: 2, name: "동경규동(강동역점)", breakfast: 'O', lunch: 'O', dinner: 'O', category: "일식" },
    { id: 3, name: "뚜레쥬르(카페강동역점)", breakfast: 'O', lunch: 'O', dinner: 'X', category: "카페/디저트" },
    { id: 4, name: "래빗온더터틀", breakfast: 'O', lunch: 'O', dinner: 'X', category: "카페/디저트" },
    { id: 5, name: "롯데리아(길동점)", breakfast: 'O', lunch: 'O', dinner: 'X', category: "기타" },
    { id: 6, name: "만랩커피(강동ECT점)", breakfast: 'O', lunch: 'O', dinner: 'X', category: "카페/디저트" },
    { id: 7, name: "매머드익스프레스 강동역점", breakfast: 'O', lunch: 'O', dinner: 'X', category: "카페/디저트" },
    { id: 8, name: "밥쁘다", breakfast: 'O', lunch: 'O', dinner: 'X', category: "한식" },
    { id: 9, name: "백년국수", breakfast: 'O', lunch: 'O', dinner: 'O', category: "한식" },
    { id: 10, name: "뱃살도둑(강동점)", breakfast: 'O', lunch: 'O', dinner: 'X', category: "기타" },
    { id: 11, name: "본가왕뼈감자탕(길동사거리점)", breakfast: 'O', lunch: 'O', dinner: 'O', category: "한식" },
    { id: 12, name: "빵장수단팥빵(천호점)", breakfast: 'O', lunch: 'O', dinner: 'X', category: "카페/디저트" },
    { id: 13, name: "빽다방(강동역헤르셔점)", breakfast: 'O', lunch: 'O', dinner: 'X', category: "카페/디저트" },
    { id: 14, name: "샐러그리티", breakfast: 'O', lunch: 'O', dinner: 'X', category: "기타" },
    { id: 15, name: "샐러드아월스어클락", breakfast: 'O', lunch: 'O', dinner: 'X', category: "양식" },
    { id: 16, name: "샐러디(강동역점)", breakfast: 'O', lunch: 'O', dinner: 'X', category: "카페/디저트" },
    { id: 17, name: "생달막국수", breakfast: 'O', lunch: 'O', dinner: 'O', category: "한식" },
    { id: 18, name: "서울감자탕", breakfast: 'O', lunch: 'O', dinner: 'O', category: "한식" },
    { id: 19, name: "선비꼬마김밥(강동역점)", breakfast: 'O', lunch: 'O', dinner: 'X', category: "한식" },
    { id: 20, name: "설담재(강동점)", breakfast: 'O', lunch: 'O', dinner: 'O', category: "기타" },
    { id: 21, name: "스타벅스(강동역점)", breakfast: 'O', lunch: 'O', dinner: 'X', category: "카페/디저트" },
    { id: 22, name: "스타벅스(천호대로길동점)", breakfast: 'O', lunch: 'O', dinner: 'X', category: "카페/디저트" },
    { id: 23, name: "슬로우캘리(강동역점)", breakfast: 'O', lunch: 'O', dinner: 'X', category: "기타" },
    { id: 24, name: "써브웨이(강동성심병원점)", breakfast: 'O', lunch: 'O', dinner: 'X', category: "기타" },
    { id: 25, name: "얌샘김밥(강동역점)", breakfast: 'O', lunch: 'O', dinner: 'X', category: "한식" },
    { id: 26, name: "오쏘헬씨", breakfast: 'O', lunch: 'O', dinner: 'X', category: "기타" },
    { id: 27, name: "이디야(강동역점)", breakfast: 'O', lunch: 'O', dinner: 'X', category: "카페/디저트" },
    { id: 28, name: "가마솥순대국밥(강동역점)", breakfast: 'O', lunch: 'O', dinner: 'O', category: "한식" },
    { id: 29, name: "전주콩뿌리콩나물국밥", breakfast: 'O', lunch: 'O', dinner: 'O', category: "한식" },
    { id: 30, name: "죠샌드위치(강동역익스프레스점)", breakfast: 'O', lunch: 'O', dinner: 'X', category: "양식" },
    { id: 31, name: "청담동마녀김밥(강동점)", breakfast: 'O', lunch: 'O', dinner: 'X', category: "한식" },
    { id: 32, name: "치코스", breakfast: 'O', lunch: 'O', dinner: 'X', category: "기타" },
    { id: 33, name: "카페63도", breakfast: 'O', lunch: 'O', dinner: 'X', category: "카페/디저트" },
    { id: 34, name: "코코플랑", breakfast: 'O', lunch: 'O', dinner: 'X', category: "기타" },
    { id: 35, name: "투썸플레이스(강동역점)", breakfast: 'O', lunch: 'O', dinner: 'X', category: "기타" },
    { id: 36, name: "파리바게뜨(강동성내점)", breakfast: 'O', lunch: 'O', dinner: 'X', category: "카페/디저트" },
    { id: 37, name: "파리바게뜨(강동역점)", breakfast: 'O', lunch: 'O', dinner: 'X', category: "카페/디저트" },
    { id: 38, name: "강남교자(강동역점)", breakfast: 'X', lunch: 'O', dinner: 'O', category: "기타" },
    { id: 39, name: "강동면옥(강동점)", breakfast: 'X', lunch: 'O', dinner: 'O', category: "한식" },
    { id: 40, name: "강동호치민", breakfast: 'X', lunch: 'O', dinner: 'O', category: "중식/아시안" },
    { id: 41, name: "강릉장칼(강동역점)", breakfast: 'X', lunch: 'O', dinner: 'O', category: "한식" },
    { id: 42, name: "과일의시작 카페야미(강동점)", breakfast: 'O', lunch: 'O', dinner: 'X', category: "카페/디저트" },
    { id: 43, name: "금돈김치마을", breakfast: 'X', lunch: 'O', dinner: 'O', category: "한식" },
    { id: 44, name: "꿀꿀 진순대국", breakfast: 'X', lunch: 'O', dinner: 'O', category: "한식" },
    { id: 45, name: "늘봄두루치기김치찌개", breakfast: 'X', lunch: 'O', dinner: 'O', category: "한식" },
    { id: 46, name: "대삼박이", breakfast: 'X', lunch: 'O', dinner: 'O', category: "기타" },
    { id: 47, name: "돈까스랑 칼국수랑", breakfast: 'X', lunch: 'O', dinner: 'O', category: "한식" },
    { id: 48, name: "라라포 분짜 쌀국수", breakfast: 'X', lunch: 'O', dinner: 'O', category: "한식" },
    { id: 49, name: "루벨(강동점)", breakfast: 'X', lunch: 'O', dinner: 'X', category: "배식" },
    { id: 50, name: "맘스터치(강동역점)", breakfast: 'X', lunch: 'O', dinner: 'X', category: "햄버거" },
    { id: 51, name: "맛있는닭한마리", breakfast: 'X', lunch: 'O', dinner: 'O', category: "기타" },
    { id: 52, name: "맛쟁이떡볶이(강동역점)", breakfast: 'X', lunch: 'O', dinner: 'X', category: "분식" },
    { id: 53, name: "모리향(강동점)", breakfast: 'X', lunch: 'O', dinner: 'O', category: "기타" },
    { id: 54, name: "모범떡볶이(길동점)", breakfast: 'X', lunch: 'O', dinner: 'O', category: "분식" },
    { id: 55, name: "미리내경양식", breakfast: 'X', lunch: 'O', dinner: 'O', category: "기타" },
    { id: 56, name: "미식미객", breakfast: 'X', lunch: 'O', dinner: 'O', category: "기타" },
    { id: 57, name: "미화동", breakfast: 'X', lunch: 'O', dinner: 'O', category: "기타" },
    { id: 58, name: "바른보쌈1990(강동점)", breakfast: 'X', lunch: 'O', dinner: 'O', category: "한식" },
    { id: 59, name: "백채김치찌개 강동역점", breakfast: 'X', lunch: 'O', dinner: 'O', category: "한식" },
    { id: 60, name: "보돌미역(강동역점)", breakfast: 'X', lunch: 'O', dinner: 'O', category: "기타" },
    { id: 61, name: "보배반점(길동점)", breakfast: 'X', lunch: 'O', dinner: 'O', category: "기타" },
    { id: 62, name: "본죽&비빔밥(강동성심병원점)", breakfast: 'X', lunch: 'O', dinner: 'O', category: "한식" },
    { id: 63, name: "봉평막국수.보쌈", breakfast: 'X', lunch: 'O', dinner: 'O', category: "한식" },
    { id: 64, name: "삼삼뼈국(강동점)", breakfast: 'X', lunch: 'O', dinner: 'O', category: "기타" },
    { id: 65, name: "성내맛집", breakfast: 'X', lunch: 'O', dinner: 'O', category: "기타" },
    { id: 66, name: "성화마라탕(강동점)", breakfast: 'X', lunch: 'O', dinner: 'O', category: "중식/아시안" },
    { id: 67, name: "소담촌(강동역점)", breakfast: 'X', lunch: 'O', dinner: 'O', category: "기타" },
    { id: 68, name: "순복이네 손맛집", breakfast: 'X', lunch: 'O', dinner: 'O', category: "기타" },
    { id: 69, name: "양촌리", breakfast: 'X', lunch: 'O', dinner: 'O', category: "기타" },
    { id: 70, name: "오형제반점(길동사거리점)", breakfast: 'X', lunch: 'O', dinner: 'O', category: "기타" },
    { id: 71, name: "온유나베", breakfast: 'X', lunch: 'O', dinner: 'O', category: "기타" },
    { id: 72, name: "온정담", breakfast: 'X', lunch: 'O', dinner: 'O', category: "기타" },
    { id: 73, name: "와바닭강정", breakfast: 'X', lunch: 'O', dinner: 'X', category: "기타" },
    { id: 74, name: "우리왕갈비탕", breakfast: 'X', lunch: 'O', dinner: 'O', category: "한식" },
    { id: 75, name: "우미관", breakfast: 'X', lunch: 'O', dinner: 'O', category: "기타" },
    { id: 76, name: "육대장 강동성심병원", breakfast: 'X', lunch: 'O', dinner: 'O', category: "기타" },
    { id: 77, name: "이삭토스트(강동성심병원점)", breakfast: 'X', lunch: 'O', dinner: 'X', category: "기타" },
    { id: 78, name: "재수돈감자탕 강동역점", breakfast: 'X', lunch: 'O', dinner: 'O', category: "한식" },
    { id: 79, name: "전통춘천닭갈비", breakfast: 'X', lunch: 'O', dinner: 'O', category: "한식" },
    { id: 80, name: "죠스떡볶이(강동역점)", breakfast: 'X', lunch: 'O', dinner: 'X', category: "분식" },
    { id: 81, name: "청년다방(강동역점)", breakfast: 'X', lunch: 'O', dinner: 'O', category: "기타" },
    { id: 82, name: "칠갑산숯불갈비", breakfast: 'X', lunch: 'O', dinner: 'O', category: "한식" },
    { id: 83, name: "키츠네", breakfast: 'X', lunch: 'O', dinner: 'O', category: "기타" },
    { id: 84, name: "팬 파스타 8393", breakfast: 'X', lunch: 'O', dinner: 'O', category: "양식" },
    { id: 85, name: "포아이니Pro 강동점", breakfast: 'X', lunch: 'O', dinner: 'O', category: "기타" },
    { id: 86, name: "포케올데이(길동사거리점)", breakfast: 'X', lunch: 'O', dinner: 'X', category: "카페/디저트" },
    { id: 87, name: "프랭크버거(강동역점)", breakfast: 'X', lunch: 'O', dinner: 'X', category: "기타" },
    { id: 88, name: "한솥도시락(강동성심병원점)", breakfast: 'X', lunch: 'O', dinner: 'X', category: "기타" },
    { id: 89, name: "한양진순대국", breakfast: 'X', lunch: 'O', dinner: 'O', category: "한식" },
    { id: 90, name: "햄찌와베찌(강동점)", breakfast: 'X', lunch: 'O', dinner: 'X', category: "기타" },
    { id: 91, name: "홍순우 홍제동순두부우동국수(강동역점)", breakfast: 'X', lunch: 'O', dinner: 'O', category: "한식" },
    { id: 92, name: "홍콩", breakfast: 'X', lunch: 'O', dinner: 'O', category: "기타" },
    { id: 93, name: "힐링차이나", breakfast: 'X', lunch: 'O', dinner: 'O', category: "기타" },
    { id: 94, name: "우리콩 손두부", breakfast: 'X', lunch: 'O', dinner: 'O', category: "기타" }
];